# Generated by Django 5.2.7 on 2025-10-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
