# Generated by Django 5.2.7 on 2025-11-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles_pacientes/'),
        ),
    ]
