# Generated by Django 5.2.8 on 2025-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_remove_paciente_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
