# Generated by Django 5.2.8 on 2025-12-04 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_paciente_fecha_ingreso_analisisimagen_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
